import React from 'react';
import type { Metadata } from 'next';
import { Header } from '../components/generic/Header/Header';
import { Golos } from './fonts';
import '../styles/globals.scss';
import { Footer } from '@/components/generic/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Golos.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
